-- Write your PostgreSQL query statement below
SELECT CUSTOMER_ID 
FROM CUSTOMER_TRANSACTIONS
GROUP BY CUSTOMER_ID 
HAVING COUNT(*) FILTER (WHERE TRANSACTION_TYPE = 'purchase') > 2 
    AND MAX(TRANSACTION_DATE) - MIN(TRANSACTION_DATE) >= 30
    AND (COUNT(*) FILTER (WHERE TRANSACTION_TYPE = 'refund') / COUNT(*)::NUMERIC) < 0.20
ORDER BY CUSTOMER_ID ASC;
