WITH PEAK_HOURS AS (
    SELECT 
        CUSTOMER_ID,
        COUNT(*) AS TOTAL_ORDERS,

        ROUND(
            (
                COUNT(*) FILTER (
                    WHERE (ORDER_TIMESTAMP::TIME BETWEEN '11:00'::TIME AND '14:00'::TIME)
                       OR (ORDER_TIMESTAMP::TIME BETWEEN '18:00'::TIME AND '21:00'::TIME)
                )::NUMERIC
                / COUNT(*)::NUMERIC
            ) * 100.0) AS PEAK_HOUR_PERCENTAGE,

        ROUND(
            SUM(ORDER_RATING) FILTER (WHERE ORDER_RATING IS NOT NULL)::NUMERIC
            /
            COUNT(*) FILTER (WHERE ORDER_RATING IS NOT NULL)::NUMERIC,
        2) AS AVERAGE_RATING

    FROM RESTAURANT_ORDERS
    GROUP BY CUSTOMER_ID
    HAVING 
        COUNT(*) FILTER (WHERE ORDER_RATING IS NOT NULL) >= (COUNT(*) / 2.0)
)

SELECT *
FROM PEAK_HOURS
WHERE PEAK_HOUR_PERCENTAGE > 60.0
  AND AVERAGE_RATING >= 4.0 AND TOTAL_ORDERS > 2
ORDER BY AVERAGE_RATING DESC, CUSTOMER_ID DESC;

