WITH BASE AS (
    SELECT
        USER_ID,
        PLAN_NAME,
        MONTHLY_AMOUNT,
        EVENT_TYPE,
        EVENT_DATE,
        MAX(EVENT_DATE) OVER (PARTITION BY USER_ID) -
        MIN(EVENT_DATE) OVER (PARTITION BY USER_ID) AS DAYS_AS_SUBSCRIBER,
        MAX(MONTHLY_AMOUNT) OVER (PARTITION BY USER_ID) AS MAX_HISTORICAL_AMOUNT,
        ROW_NUMBER() OVER (
            PARTITION BY USER_ID 
            ORDER BY EVENT_DATE DESC
        ) AS rn
    FROM SUBSCRIPTION_EVENTS
)
SELECT
    USER_ID,
    PLAN_NAME AS CURRENT_PLAN,
    MONTHLY_AMOUNT AS CURRENT_MONTHLY_AMOUNT,
    MAX_HISTORICAL_AMOUNT,
    DAYS_AS_SUBSCRIBER
FROM BASE b
WHERE
    rn = 1  -- latest event (ACTIVE)
    AND b.EVENT_TYPE <> 'cancel'
    AND EXISTS (
        SELECT 1 
        FROM SUBSCRIPTION_EVENTS s
        WHERE s.USER_ID = b.USER_ID
        AND s.EVENT_TYPE = 'downgrade'
    )
    AND DAYS_AS_SUBSCRIBER >= 60
    AND MONTHLY_AMOUNT < (MAX_HISTORICAL_AMOUNT / 2.0)
ORDER BY DAYS_AS_SUBSCRIBER DESC, USER_ID ASC;




-- Write your PostgreSQL query statement below
-- WITH ACTIVE AS (
--     SELECT DISTINCT ON (USER_ID) * FROM SUBSCRIPTION_EVENTS WHERE EVENT_TYPE <> 'cancel' ORDER BY USER_ID, EVENT_DATE DESC
-- ),
-- DOWNGRADE AS(
--     SELECT DISTINCT USER_ID FROM SUBSCRIPTION_EVENTS WHERE EVENT_TYPE = 'downgrade'
-- ),
-- REVENUE AS (
--     SELECT DISTINCT ON(USER_ID) USER_ID, MONTHLY_AMOUNT AS MAX_HISTORICAL_AMOUNT, EVENT_DATE FROM SUBSCRIPTION_EVENTS ORDER BY USER_ID, MONTHLY_AMOUNT DESC
-- ),
-- SINCE AS(
--     SELECT USER_ID, MAX(EVENT_DATE) - MIN(EVENT_DATE) AS DAYS_AS_SUBSCRIBER FROM SUBSCRIPTION_EVENTS GROUP BY USER_ID
-- )
-- SELECT ACTIVE.USER_ID,
--     ACTIVE.PLAN_NAME AS CURRENT_PLAN,
--     ACTIVE.MONTHLY_AMOUNT AS CURRENT_MONTHLY_AMOUNT,
--     MAX_HISTORICAL_AMOUNT,
--     DAYS_AS_SUBSCRIBER
-- FROM ACTIVE 
-- JOIN DOWNGRADE 
--     ON ACTIVE.USER_ID = DOWNGRADE.USER_ID
-- JOIN REVENUE
--     ON ACTIVE.USER_ID = REVENUE.USER_ID
-- JOIN SINCE
-- ON ACTIVE.USER_ID = SINCE.USER_ID
-- WHERE DAYS_AS_SUBSCRIBER >= 60 AND ACTIVE.MONTHLY_AMOUNT < (MAX_HISTORICAL_AMOUNT / 2.0)
-- ORDER BY DAYS_AS_SUBSCRIBER DESC, USER_ID ASC;
