WITH PER_WEEK AS(
    SELECT EMPLOYEE_ID,
        (MEETING_DATE - (EXTRACT(ISODOW FROM MEETING_DATE)::INT - 1))::DATE AS WEEK_MONDAY,
        SUM(DURATION_HOURS) AS TOTAL_HOURS
    FROM 
    MEETINGS
    GROUP BY EMPLOYEE_ID,
        WEEK_MONDAY
),
HEAVY_WEEKS AS (
    SELECT EMPLOYEE_ID,
        COUNT(*) AS HEAVY
    FROM PER_WEEK
    WHERE TOTAL_HOURS  > 20
    GROUP BY EMPLOYEE_ID
),
COUNT_WEEKS AS(
    SELECT EMPLOYEE_ID,
        HEAVY
    FROM HEAVY_WEEKS
    WHERE HEAVY >= 2
)
SELECT E.EMPLOYEE_ID, 
    EMPLOYEE_NAME, 
    DEPARTMENT,
    HEAVY AS MEETING_HEAVY_WEEKS
FROM COUNT_WEEKS JOIN EMPLOYEES E
ON E.EMPLOYEE_ID = COUNT_WEEKS.EMPLOYEE_ID
ORDER BY HEAVY DESC,
    EMPLOYEE_NAME ASC;
