-- Write your PostgreSQL query statement below
SELECT CUSTOMER_ID FROM 
(SELECT CUSTOMER_ID,PRODUCT_KEY FROM CUSTOMER GROUP BY CUSTOMER_ID,PRODUCT_KEY) 
GROUP BY CUSTOMER_ID HAVING COUNT(DISTINCT PRODUCT_KEY) = (SELECT COUNT(*) FROM PRODUCT);
