-- Write your PostgreSQL query statement below
SELECT M.EMPLOYEE_ID, M.NAME,COUNT(*) AS REPORTS_COUNT, ROUND(AVG(E.AGE)) AS AVERAGE_AGE
FROM EMPLOYEES E JOIN EMPLOYEES M ON E.REPORTS_TO = M.EMPLOYEE_ID
GROUP BY M.EMPLOYEE_ID, M.NAME
ORDER BY M.EMPLOYEE_ID;
