-- Write your PostgreSQL query statement below
SELECT TRANSACTION_DATE,
    COALESCE(SUM(AMOUNT) FILTER (WHERE AMOUNT % 2 = 1), 0) AS ODD_SUM,
    COALESCE(SUM(AMOUNT) FILTER (WHERE AMOUNT % 2 = 0), 0) AS EVEN_SUM 
FROM TRANSACTIONS 
GROUP BY TRANSACTION_DATE
ORDER BY TRANSACTION_DATE;
