-- Write your PostgreSQL query statement below
SELECT S.USER_ID, 
    ROUND(COUNT(*) FILTER (WHERE ACTION='confirmed') / COUNT(*)::NUMERIC, 2) AS CONFIRMATION_RATE 
FROM SIGNUPS S LEFT JOIN CONFIRMATIONS C 
ON S.USER_ID = C.USER_ID
GROUP BY S.USER_ID;
