-- Write your PostgreSQL query statement below
WITH TAB1 AS 
(SELECT DISTINCT ON (CUSTOMER_ID) 
    DELIVERY_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    CUSTOMER_PREF_DELIVERY_DATE AS PREF
FROM DELIVERY 
ORDER BY CUSTOMER_ID, ORDER_DATE ASC)
SELECT ROUND(
        (COUNT(*) FILTER (WHERE ORDER_DATE = PREF) * 100.0) / COUNT(*)
    , 2) AS IMMEDIATE_PERCENTAGE 
FROM TAB1;
