-- Write your PostgreSQL query statement below
SELECT PP1.PRODUCT_ID AS PRODUCT1_ID,
    PP2.PRODUCT_ID AS PRODUCT2_ID,
    PI1.CATEGORY AS PRODUCT1_CATEGORY,
    PI2.CATEGORY AS PRODUCT2_CATEGORY,
    COUNT(DISTINCT PP1.USER_ID) AS CUSTOMER_COUNT
FROM PRODUCTPURCHASES PP1 
JOIN PRODUCTPURCHASES PP2 
    ON PP1.PRODUCT_ID <> PP2.PRODUCT_ID 
    AND PP1.PRODUCT_ID < PP2.PRODUCT_ID 
    AND PP1.USER_ID = PP2.USER_ID
JOIN PRODUCTINFO PI1 
    ON PI1.PRODUCT_ID = PP1.PRODUCT_ID
JOIN PRODUCTINFO PI2
    ON PI2.PRODUCT_ID = PP2.PRODUCT_ID
GROUP BY 
    PP1.PRODUCT_ID,
    PP2.PRODUCT_ID,
    PI1.CATEGORY, 
    PI2.CATEGORY
HAVING COUNT(DISTINCT PP1.USER_ID) >= 3
ORDER BY CUSTOMER_COUNT DESC, 
    PP1.PRODUCT_ID ASC, 
    PP2.PRODUCT_ID ASC;
