-- Write your PostgreSQL query statement below
SELECT CONTEST_ID, ROUND((COUNT(*) * 100.0/(SELECT COUNT(*) FROM USERS)),2) AS PERCENTAGE FROM
REGISTER R JOIN USERS U ON R.USER_ID = U.USER_ID
GROUP BY CONTEST_ID
ORDER BY PERCENTAGE DESC, CONTEST_ID ASC;
