WITH DIFFERENT AS (
    SELECT STORE_ID FROM INVENTORY GROUP BY STORE_ID HAVING COUNT(DISTINCT PRODUCT_NAME) > 2
),
MAXIMUM AS (
    SELECT DISTINCT ON(STORE_ID)
    *
    FROM INVENTORY
    WHERE STORE_ID IN (SELECT * FROM DIFFERENT)
    ORDER BY STORE_ID, PRICE DESC
),
MINIMUM AS 
(
    SELECT DISTINCT ON(STORE_ID)
    * FROM INVENTORY 
    WHERE STORE_ID IN (SELECT * FROM DIFFERENT)
    ORDER BY STORE_ID, PRICE ASC
)
SELECT MA.STORE_ID, 
    ST.STORE_NAME,
    ST.LOCATION,
    MA.PRODUCT_NAME AS MOST_EXP_PRODUCT,
    MI.PRODUCT_NAME AS CHEAPEST_PRODUCT,
    ROUND((MI.QUANTITY / MA.QUANTITY::NUMERIC),2) AS IMBALANCE_RATIO
FROM MAXIMUM MA 
JOIN MINIMUM MI 
    ON MA.STORE_ID = MI.STORE_ID 
JOIN STORES ST
    ON MA.STORE_ID = ST.STORE_ID
WHERE MA.QUANTITY < MI.QUANTITY
ORDER BY IMBALANCE_RATIO DESC, 
    STORE_NAME ASC;
