-- Write your PostgreSQL query statement below
SELECT ID, (CASE WHEN ID IN (SELECT MAX(ID) FROM SEAT) AND MOD(ID, 2) <> 0 THEN STUDENT WHEN MOD(ID, 2) = 0 THEN LAG(STUDENT) OVER (ORDER BY ID) ELSE LEAD(STUDENT) OVER (ORDER BY ID) END) AS STUDENT
FROM SEAT 
ORDER BY ID ASC;
