-- Write your PostgreSQL query statement below
WITH TAB AS
(SELECT REQUESTER_ID AS ID,COUNT(*) AS NUM FROM  
(SELECT REQUESTER_ID FROM REQUESTACCEPTED
UNION ALL 
SELECT ACCEPTER_ID AS REQUESTER_ID FROM REQUESTACCEPTED) GROUP BY REQUESTER_ID)
SELECT ID,NUM FROM TAB WHERE NUM = (SELECT MAX(NUM) FROM TAB);
