-- Write your PostgreSQL query statement below
SELECT QUERY_NAME, 
ROUND(AVG(RATING::DECIMAL / POSITION),2) AS QUALITY,
ROUND(100.0 * SUM(CASE WHEN RATING < 3 THEN 1 ELSE 0 END)/ COUNT(*), 2) AS POOR_QUERY_PERCENTAGE
FROM QUERIES GROUP BY QUERY_NAME; 
