-- Write your PostgreSQL query statement below
WITH CATEGORIES AS (
    SELECT PI1.CATEGORY AS CATEGORY1,
        ARRAY_AGG(DISTINCT PI1.PRODUCT_ID) AS IDS1,
        PI2.CATEGORY AS CATEGORY2,
        ARRAY_AGG(DISTINCT PI2.PRODUCT_ID) AS IDS2
    FROM PRODUCTINFO PI1 
    CROSS JOIN PRODUCTINFO PI2
    WHERE PI1.CATEGORY < PI2.CATEGORY
    GROUP BY PI1.CATEGORY, PI2.CATEGORY
    ORDER BY PI1.CATEGORY, PI2.CATEGORY
),
FIND AS(
    SELECT USER_ID, ARRAY_AGG(DISTINCT PRODUCT_ID) AS PURCHASES
    FROM PRODUCTPURCHASES
    GROUP BY USER_ID
)
SELECT C.CATEGORY1,
    C.CATEGORY2,
    COUNT(*) AS CUSTOMER_COUNT
FROM CATEGORIES c
JOIN FIND f
    ON (
        F.PURCHASES && C.IDS1
        AND
        F.PURCHASES && C.IDS2
    )
GROUP BY C.CATEGORY1,
    C.CATEGORY2
HAVING COUNT(*) > 2
ORDER BY CUSTOMER_COUNT DESC,
    C.CATEGORY1,
    C.CATEGORY2;
