-- Write your PostgreSQL query statement below
-- SELECT NAME,AMOUNT AS BALANCE FROM 
SELECT NAME,SUM(AMOUNT) AS BALANCE 
FROM TRANSACTIONS JOIN USERS ON TRANSACTIONS.ACCOUNT = USERS.ACCOUNT 
GROUP BY TRANSACTIONS.ACCOUNT, NAME 
HAVING SUM(AMOUNT) > 10000;
