-- Write your PostgreSQL query statement below
SELECT USER_ID,
    COALESCE(ROUND(AVG(ACTIVITY_DURATION) FILTER (WHERE ACTIVITY_TYPE = 'free_trial'), 2), 0.00) AS TRIAL_AVG_DURATION,
    COALESCE(ROUND(AVG(ACTIVITY_DURATION) FILTER (WHERE ACTIVITY_TYPE = 'paid'), 2), 0.00) AS PAID_AVG_DURATION
FROM USERACTIVITY
GROUP BY USER_ID HAVING USER_ID IN 
    (SELECT DISTINCT USER_ID 
        FROM USERACTIVITY 
        WHERE ACTIVITY_TYPE = 'paid'
    )
ORDER BY USER_ID ASC;
