WITH TAB1 AS (
    SELECT 
        EMPLOYEE_ID,
        REVIEW_ID,
        REVIEW_DATE,
        RATING,
        ROW_NUMBER() OVER (
            PARTITION BY EMPLOYEE_ID 
            ORDER BY REVIEW_DATE DESC
        ) AS RN
    FROM PERFORMANCE_REVIEWS
), FILTERED AS(
    SELECT * FROM TAB1 WHERE RN <= 3
), AGG AS (
    SELECT EMPLOYEE_ID,
    MIN(RATING) FILTER(WHERE RN = 1) AS LATEST,
    MIN(RATING) FILTER(WHERE RN = 2) AS MIDDLE,
    MIN(RATING) FILTER(WHERE RN = 3) AS OLD
    FROM FILTERED GROUP BY EMPLOYEE_ID
)
SELECT AGG.EMPLOYEE_ID, 
    EMPLOYEES.NAME, 
    LATEST - OLD AS IMPROVEMENT_SCORE 
FROM AGG 
JOIN EMPLOYEES 
ON AGG.EMPLOYEE_ID = EMPLOYEES.EMPLOYEE_ID
WHERE LATEST > MIDDLE 
    AND MIDDLE > OLD
ORDER BY IMPROVEMENT_SCORE DESC, NAME ASC;
