-- Write your PostgreSQL query statement below
SELECT USER_ID AS BUYER_ID, 
    JOIN_DATE, 
    COUNT(ORDER_ID) AS ORDERS_IN_2019 
FROM USERS 
LEFT JOIN 
    ORDERS
ON USERS.USER_ID = ORDERS.BUYER_ID
AND 
EXTRACT(YEAR FROM ORDER_DATE) = 2019
GROUP BY USER_ID, JOIN_DATE;
