-- Write your PostgreSQL query statement below
SELECT 
    PRODUCT_ID AS PRODUCT_ID, 
    YEAR AS FIRST_YEAR, 
    QUANTITY AS QUANTITY, 
    PRICE AS PRICE
FROM SALES 
WHERE (PRODUCT_ID , YEAR) IN (
    SELECT PRODUCT_ID, MIN(YEAR) AS YEAR 
    FROM SALES 
    GROUP BY PRODUCT_ID
);


