SELECT VISITED_ON,
    SUM(AMOUNT) OVER (ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AMOUNT,
    ROUND(SUM(AMOUNT) OVER (ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) / 7.0,2) AS AVERAGE_AMOUNT
FROM (SELECT 
        VISITED_ON ,
        SUM(AMOUNT) AS AMOUNT
    FROM CUSTOMER 
    GROUP BY VISITED_ON
    )
ORDER BY VISITED_ON ASC OFFSET 6;

