-- Write your PostgreSQL query statement below
SELECT E.EMPLOYEE_ID
FROM EMPLOYEES E LEFT JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE E.SALARY < 30000 AND M.EMPLOYEE_ID IS NULL AND E.MANAGER_ID IS NOT NULL
ORDER BY E.EMPLOYEE_ID;
