WITH RECURSIVE HIERARCHY AS (
    SELECT EMPLOYEE_ID,
        EMPLOYEE_NAME,
        MANAGER_ID,
        DEPARTMENT,
        SALARY,
        1 AS LEVEL,
        EMPLOYEE_ID AS ROOT_MANAGER
    FROM EMPLOYEES 
    UNION ALL
    SELECT E.EMPLOYEE_ID,
        E.EMPLOYEE_NAME,
        E.MANAGER_ID,
        E.DEPARTMENT,
        E.SALARY,
        H.LEVEL + 1 AS LEVEL,
        H.ROOT_MANAGER
    FROM EMPLOYEES E JOIN HIERARCHY H
    ON E.MANAGER_ID = H.EMPLOYEE_ID 
),
AGG AS (
    SELECT ROOT_MANAGER AS EMPLOYEE_ID,
        COUNT(*) - 1 AS TEAM_SIZE,
        SUM(SALARY) AS BUDGET
    FROM HIERARCHY
    GROUP BY ROOT_MANAGER
),
FINAL_HIERARCHY AS (
    SELECT *
    FROM HIERARCHY
    WHERE ROOT_MANAGER IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL)
)
SELECT 
    FH.EMPLOYEE_ID,
    FH.EMPLOYEE_NAME,
    FH.LEVEL,
    G.TEAM_SIZE,
    G.BUDGET
FROM FINAL_HIERARCHY FH
JOIN AGG G
    ON FH.EMPLOYEE_ID = G.EMPLOYEE_ID
ORDER BY 
    FH.LEVEL ASC,
    G.BUDGET DESC,
    FH.EMPLOYEE_NAME ASC;
