-- Write your PostgreSQL query statement below
SELECT 'Low Salary' AS CATEGORY, COUNT(*) AS ACCOUNTS_COUNT FROM ACCOUNTS WHERE INCOME < 20000
UNION ALL
SELECT 'Average Salary' AS CATEGORY , COUNT(*) AS ACCOUNTS_COUNT FROM ACCOUNTS WHERE INCOME >= 20000 ANd INCOME <= 50000
UNION ALL
SELECT 'High Salary' AS CATEGORY, COUNT(*) AS ACCOUNTS_COUNT FROM ACCOUNTS WHERE INCOME > 50000;
