SELECT S.STUDENT_ID,S.STUDENT_NAME,B.SUBJECT_NAME,COUNT(E.SUBJECT_NAME) AS ATTENDED_EXAMS 
FROM students s
CROSS JOIN subjects b
LEFT JOIN examinations e 
    ON s.student_id = e.student_id 
   AND b.subject_NAME = e.subject_NAME
GROUP BY S.STUDENT_ID, S.STUDENT_NAME, B.SUBJECT_NAME ORDER BY S.STUDENT_ID, S.STUDENT_NAME; 
