-- Write your PostgreSQL query statement below
SELECT  TO_CHAR(TRANS_DATE::date, 'YYYY-MM') AS MONTH, 
    COUNTRY, 
    COUNT(*) AS TRANS_COUNT,
    COALESCE(COUNT(*) FILTER (WHERE STATE = 'approved'),0) AS APPROVED_COUNT,
    SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
    COALESCE(SUM(AMOUNT) FILTER (WHERE STATE = 'approved'), 0) AS APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS 
GROUP BY TO_CHAR(TRANS_DATE::date, 'YYYY-MM'), COUNTRY;
