WITH POS AS (
    SELECT *, 
           ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY TEST_DATE) AS RNK_POS
    FROM COVID_TESTS
    WHERE RESULT = 'Positive'
), 
NEG AS (
    SELECT *, 
           ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY TEST_DATE) AS RNK_NEG
    FROM COVID_TESTS
    WHERE RESULT = 'Negative'
)
SELECT POS.PATIENT_ID,
       PATIENT_NAME,
       AGE,
       (NEG.TEST_DATE - POS.TEST_DATE) AS RECOVERY_TIME
FROM POS
JOIN NEG
    ON POS.PATIENT_ID = NEG.PATIENT_ID
   AND POS.TEST_DATE < NEG.TEST_DATE
JOIN PATIENTS P
    ON P.PATIENT_ID = POS.PATIENT_ID
WHERE RNK_POS = 1
  AND NEG.TEST_DATE = (
        SELECT MIN(TEST_DATE)
        FROM NEG N2
        WHERE N2.PATIENT_ID = POS.PATIENT_ID
          AND N2.TEST_DATE > POS.TEST_DATE
    )
ORDER BY RECOVERY_TIME ASC,
         PATIENT_NAME ASC;
