-- Write your PostgreSQL query statement below
SELECT D.NAME AS DEPARTMENT,E.NAME AS EMPLOYEE,SALARY 
FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID 
JOIN (
    SELECT ID,
    DENSE_RANK() OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RANK 
    FROM EMPLOYEE ORDER BY DEPARTMENTID
    ) RANKED 
ON E.ID = RANKED.ID 
WHERE RANK BETWEEN 1 AND 3;
