-- Write your PostgreSQL query statement below
SELECT PERSON_NAME FROM 
    (SELECT TURN,
        PERSON_ID,
        PERSON_NAME,
        WEIGHT,
        SUM(WEIGHT) OVER (ORDER BY TURN) AS TOTAL_WEIGHT 
    FROM QUEUE)
WHERE TOTAL_WEIGHT <= 1000 
ORDER BY TOTAL_WEIGHT DESC LIMIT 1;
