name: Sync Leetcode

on:
  workflow_dispatch: # Allows you to click a button to run it manually
  schedule:
    - cron: "0 0 * * *" # Runs completely automatically every single night at midnight UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: raphael-p/leetcode-sync@v1.7.1
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-submissions
